
version: 0.2

phases:
  install:
    commands:
      - echo "Preparing for S3 deployment"

  build:
    commands:
      - echo "Uploading files to S3..."
      - aws s3 sync ./dist s3://your-artifact-bucket --delete

artifacts:
  files:
    - '**/*'
