version: 0.2
phases:
  install:
    commands:
      - echo "Preparing for S3 deployment"
  build:
    commands:
      - echo "Uploading files to S3..."
      # 指定パスにアップロード（例：contents/app/）
      - aws s3 sync ./ s3://movie-dev-lp-s3-ito-01/contents/ --delete || { echo "S3 sync failed"; exit 1; }
post_build:
  commands:
      - echo "Invalidating CloudFront cache..."
      # キャッシュ無効化もパスに合わせる
      - aws cloudfront create-invalidation --distribution-id E3LKNA63UJUSGM --paths "/contents/app/*"
artifacts:
  files:
    - '**/*'