
version: 0.2
phases:
  install:
    commands:
      - cd app   # package.jsonがあるディレクトリに移動
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: app/build
